services:

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data  # ✅ Persistencia de datos
      - ./initdb/swapify_backup.dump:/docker-entrypoint-initdb.d/restore.dump:ro
      - ./initdb/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
    ports:
      - "5432:5432"
    healthcheck:  # ✅ Verifica que la DB esté lista
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./SwapifyAPI
    image: swapify-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      # Mostrar SQL en consola. Útil solo para desarrollo local.
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    depends_on:
      db:
        condition: service_healthy  # ✅ Espera a que la DB esté saludable
    restart: unless-stopped  # ✅ Reinicia si falla

  frontend:
    build: ./swapify-frontend
    image: swapify-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:  # ✅ Ahora sí se usa